create or replace package bio is
    
        procedure login (userne in BIO_USER.USERNAME%type,
                                        phone in BIO_LOG_ENTRY.UUID_PHONE%type,
                                        id_fingerp out varchar2,
                                        p_var OUT VARCHAR2);
                                        
        procedure huella (una in BIO_LOG_USER_FINGERP.UNAME%type,
        id_logd in BIO_LOG_USER_FINGERP.id_ilog%type,
        finger_tem in BIO_LOG_USER_FINGERP.FINGERPRINT_TEMPLATE%type,
        finger_im in BIO_LOG_USER_FINGERP.FINGERPRINT_image%type,
        id_user out varchar2,
        p_var OUT VARCHAR2);
        
        procedure prepago (
        fingerp_tem in bio_customer_fingerp.fingerprint_template%type,
        fingerp_im in bio_customer_fingerp.fingerprint_image%type,
        usern in BIO_DATA_CUSTOMER.USERNAME%type,
        face_p in BIO_DATA_CUSTOMER.FACE_PICTURE%type,
        dni_p in BIO_DATA_CUSTOMER.dni_PICTURE%type,
        sing_p in BIO_DATA_CUSTOMER.SIGNATURE_picture%type,
        id_cust in BIO_CUSTOMER.ICUSTOMER%type,
        id_cust_a in BIO_CUSTOMER_ASSET.ID_ASSET_CUSTOMER%type,
        id_cont in BIO_CUSTOMER_ASSET.ID_CONTRACT%type,
        res_type in BIO_CUSTOMER_ASSET.REGISTER_TYPE%type,
        id_dacu out varchar2,
        id_cusfin out varchar2,
        p_var OUT VARCHAR2);
        
        procedure prepago_discap (fingerp_temp_d in bio_rep_fingerp_discap.fingerprint_template%type,
        fingerp_im_d in bio_rep_fingerp_discap.fingerprint_image%type,
        face_p_d in bio_rep_discap.face_picture%type,
        dni_p_d in bio_rep_discap.dni_picture%type,
        sing_p_d in bio_rep_discap.singnature_picture%type,
        usern in BIO_DATA_CUSTOMER.USERNAME%type,
        face_p in BIO_DATA_CUSTOMER.FACE_PICTURE%type,
        dni_p in BIO_DATA_CUSTOMER.dni_PICTURE%type,
        sing_p in BIO_DATA_CUSTOMER.SIGNATURE_picture%type,
        pic_d in BIO_DATA_CUSTOMER.picture_discap%type,
        id_cust in BIO_CUSTOMER.ICUSTOMER%type,
        id_cust_a in BIO_CUSTOMER_ASSET.ID_ASSET_CUSTOMER%type,
        id_cont in BIO_CUSTOMER_ASSET.ID_CONTRACT%type,
        res_type in BIO_CUSTOMER_ASSET.REGISTER_TYPE%type,
        id_discap out varchar2,
        id_finge out varchar2,
        id_dacu out varchar2,
        id_cusfin out varchar2,
        p_var OUT VARCHAR2);
        
        procedure postpago (
        fingerp_tem in bio_customer_fingerp.fingerprint_template%type,
        fingerp_im in bio_customer_fingerp.fingerprint_image%type,
        usern in BIO_DATA_CUSTOMER.USERNAME%type,
        face_p in BIO_DATA_CUSTOMER.FACE_PICTURE%type,
        dni_p in BIO_DATA_CUSTOMER.dni_PICTURE%type,
        sing_p in BIO_DATA_CUSTOMER.SIGNATURE_picture%type,
        id_cust in BIO_CUSTOMER.ICUSTOMER%type,
        id_cust_a in BIO_CUSTOMER_ASSET.ID_ASSET_CUSTOMER%type,
        id_cont in BIO_CUSTOMER_ASSET.ID_CONTRACT%type,
        res_type in BIO_CUSTOMER_ASSET.REGISTER_TYPE%type,
        bank_data in BIO_BANK_DATA.BANK_DATA_TYPE%type,
        tdc_a in BIO_BANK_DATA.TDC_ADVERSE%type,
        tdc_r in BIO_BANK_DATA.TDC_REVERSE%type,
        ACC_S in BIO_BANK_DATA.ACCOUNT_STATUS%type,
        id_bank out varchar2,
        id_dacu out varchar2,
        id_cusfin out varchar2,
        p_var OUT VARCHAR2);
        
        procedure postpago_discap(fingerp_temp_d in bio_rep_fingerp_discap.fingerprint_template%type,
        fingerp_im_d in bio_rep_fingerp_discap.fingerprint_image%type,
        face_p_d in bio_rep_discap.face_picture%type,
        dni_p_d in bio_rep_discap.dni_picture%type,
        sing_p_d in bio_rep_discap.singnature_picture%type,
        usern in BIO_DATA_CUSTOMER.USERNAME%type,
        face_p in BIO_DATA_CUSTOMER.FACE_PICTURE%type,
        dni_p in BIO_DATA_CUSTOMER.dni_PICTURE%type,
        sing_p in BIO_DATA_CUSTOMER.SIGNATURE_picture%type,
        pic_d in BIO_DATA_CUSTOMER.picture_discap%type,
        id_cust in BIO_CUSTOMER.ICUSTOMER%type,
        id_cust_a in BIO_CUSTOMER_ASSET.ID_ASSET_CUSTOMER%type,
        id_cont in BIO_CUSTOMER_ASSET.ID_CONTRACT%type,
        res_type in BIO_CUSTOMER_ASSET.REGISTER_TYPE%type,
        bank_data in BIO_BANK_DATA.BANK_DATA_TYPE%type,
        tdc_a in BIO_BANK_DATA.TDC_ADVERSE%type,
        tdc_r in BIO_BANK_DATA.TDC_REVERSE%type,
        ACC_S in BIO_BANK_DATA.ACCOUNT_STATUS%type,
        id_bank out varchar2,
        id_discap out varchar2,
        id_finge out varchar2,
        id_dacu out varchar2,
        id_cusfin out varchar2,
        p_var OUT VARCHAR2);
        
end bio;