CREATE TABLE BIO_REP_FINGERP_DISCAP(
 ID_FINGERPRINT VARCHAR2(20) NOT NULL,
 FINGERPRINT_TEMPLATE CLOB NOT NULL,
 FINGERPRINT_IMAGE CLOB NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_REP_FINGERP_DISCAP PRIMARY KEY (ID_FINGERPRINT)
);

CREATE TABLE BIO_REP_DISCAP(
 ID_REPRESENTATIVE VARCHAR2(20) NOT NULL,
 ID_FINGERPRINT VARCHAR2(20) NOT NULL,
 FACE_PICTURE CLOB NOT NULL,
 DNI_PICTURE CLOB NOT NULL,
 SINGNATURE_PICTURE CLOB NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_REP_DISCAP PRIMARY KEY (ID_REPRESENTATIVE),
 CONSTRAINT FK_ID_FINGERPRINT FOREIGN KEY (ID_FINGERPRINT) REFERENCES BIO_REP_FINGERP_DISCAP (ID_FINGERPRINT)
);

CREATE TABLE BIO_CUSTOMER_FINGERP(
 ID_FINGERPRINT VARCHAR2(20) NOT NULL,
 FINGERPRINT_TEMPLATE CLOB NOT NULL,
 FINGERPRINT_IMAGE CLOB NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_CUSTOMER_FINGERP PRIMARY KEY (ID_FINGERPRINT)
);

CREATE TABLE BIO_BANK_DATA(
 ID_BANK_DATA VARCHAR2(20) NOT NULL,
 BANK_DATA_TYPE VARCHAR2(30) NOT NULL,
 TDC_ADVERSE CLOB NULL,
 TDC_REVERSE CLOB NULL,
 ACCOUNT_STATUS CLOB NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_BANK_DATA PRIMARY KEY (ID_BANK_DATA)
);

CREATE TABLE BIO_USER(
 USERNAME VARCHAR2(20) NOT NULL,
 STATUS NUMBER NOT NULL,
 TRIES NUMBER NOT NULL,
 ID_ROLE VARCHAR2(10) NOT NULL,
 ID_PERSON VARCHAR2(10) NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_USER PRIMARY KEY (USERNAME)
);

CREATE TABLE BIO_DATA_CUSTOMER(
 ID_REGISTER VARCHAR2(20) NOT NULL,
 USERNAME VARCHAR2(20) NOT NULL,
 ID_CUSTOMER_FINGERPRINT VARCHAR2(20) NULL,
 FACE_PICTURE CLOB NOT NULL,
 DNI_PICTURE CLOB NOT NULL,
 SIGNATURE_PICTURE CLOB NULL,
 ID_REPRESENTATIVE_DISCAP VARCHAR2(20) NULL,
 CREATE_AT DATE NOT NULL,
 ID_BANK_DATA VARCHAR2 (20) NULL,
 Picture_Discap clob null,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_DATA_CUSTOMER PRIMARY KEY (ID_REGISTER),
 CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES BIO_USER(USERNAME),
 CONSTRAINT FK_ID_CUSTOMER_FINGERP FOREIGN KEY (ID_CUSTOMER_FINGERPRINT) REFERENCES BIO_CUSTOMER_FINGERP(ID_FINGERPRINT),
 CONSTRAINT FK_ID_REP_DISCAP FOREIGN KEY (ID_REPRESENTATIVE_DISCAP) REFERENCES BIO_REP_DISCAP(ID_REPRESENTATIVE),
 CONSTRAINT FK_ID_BANK_DATA FOREIGN KEY (ID_BANK_DATA) REFERENCES BIO_BANK_DATA(ID_BANK_DATA)
);


CREATE TABLE BIO_LOG_ENTRY(
 ILOG VARCHAR2(20) NOT NULL,
 USNAME VARCHAR2(20) NOT NULL,
 CREATE_AT DATE NOT NULL,
 UUID_PHONE VARCHAR2(50) NOT NULL,

 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_LOG_ENTRY PRIMARY KEY (ILOG),
 CONSTRAINT FK_USNAME FOREIGN KEY (USNAME) REFERENCES BIO_USER (USERNAME)
);

CREATE TABLE BIO_LOG_USER_FINGERP(
 ID_LOG VARCHAR2(20) NOT NULL,
 ID_ILOG VARCHAR2(20) NOT NULL,
 UNAME VARCHAR2(20) NOT NULL,
 FINGERPRINT_TEMPLATE CLOB NOT NULL,
 FINGERPRINT_IMAGE CLOB NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_LOG_USER_FINGERP PRIMARY KEY (ID_LOG),
 CONSTRAINT FK_UNAME FOREIGN KEY (UNAME) REFERENCES BIO_USER (USERNAME),
 CONSTRAINT FK_ID_ILOG FOREIGN KEY (ID_ILOG) REFERENCES BIO_LOG_ENTRY (ILOG)
);

CREATE TABLE BIO_CUSTOMER_ASSET(
 ID_REGISTER VARCHAR2(20) NOT NULL,
 ID_ASSET_CUSTOMER VARCHAR2(15) NOT NULL,
 ID_CONTRACT VARCHAR2(20) NOT NULL,
 REGISTER_TYPE VARCHAR2(20) NOT NULL,
 REGISTER_STATUS INT NOT NULL,
 REGISTER_DATE DATE NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_CUSTOMER_ASSET PRIMARY KEY (ID_REGISTER,ID_ASSET_CUSTOMER),
 CONSTRAINT FK_ID_REGISTER FOREIGN KEY (ID_REGISTER) REFERENCES BIO_DATA_CUSTOMER (ID_REGISTER),
 CONSTRAINT FK_ID_ASSET_CUSTOMER FOREIGN KEY (ID_ASSET_CUSTOMER) REFERENCES BDUC.U_ASSET_CUSTOMER (ASSET_ID) 
);


CREATE TABLE BIO_CUSTOMER(
 IREGISTER VARCHAR2(20) NOT NULL,
 ICUSTOMER VARCHAR2(15) NOT NULL,
 REGISTER_STATUS INT NOT NULL,
 REGISTER_DATE DATE NOT NULL,
 
 CREATED_DT timestamp NOT NULL,
 CREATED_WHO VARCHAR2(20) NOT NULL,
 ACTIVE_DT timestamp NOT NULL,
 CHANGE_DT timestamp NOT NULL,
 CHANDE_WHO VARCHAR2(20) NOT NULL,
 INACTIVE_DT timestamp NULL,
 
 CONSTRAINT PK_BIO_CUSTOMERT PRIMARY KEY (IREGISTER,ICUSTOMER),
 CONSTRAINT FK_ICUSTOMER FOREIGN KEY (ICUSTOMER) REFERENCES BDUC.U_CUSTOMER (CUSTOMER_ID),
 CONSTRAINT FK_IREGISTER FOREIGN KEY (IREGISTER) REFERENCES BIO_DATA_CUSTOMER (ID_REGISTER)
);
